// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.11.4
// source: proto/gacha.proto

package grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// GachaServiceClient is the client API for GachaService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GachaServiceClient interface {
	Draw(ctx context.Context, in *DrawRequest, opts ...grpc.CallOption) (*DrawResponse, error)
	GetHistories(ctx context.Context, in *GetHistoriesRequest, opts ...grpc.CallOption) (*GetHistoriesResponse, error)
}

type gachaServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGachaServiceClient(cc grpc.ClientConnInterface) GachaServiceClient {
	return &gachaServiceClient{cc}
}

func (c *gachaServiceClient) Draw(ctx context.Context, in *DrawRequest, opts ...grpc.CallOption) (*DrawResponse, error) {
	out := new(DrawResponse)
	err := c.cc.Invoke(ctx, "/gacha.GachaService/Draw", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gachaServiceClient) GetHistories(ctx context.Context, in *GetHistoriesRequest, opts ...grpc.CallOption) (*GetHistoriesResponse, error) {
	out := new(GetHistoriesResponse)
	err := c.cc.Invoke(ctx, "/gacha.GachaService/GetHistories", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GachaServiceServer is the server API for GachaService service.
// All implementations must embed UnimplementedGachaServiceServer
// for forward compatibility
type GachaServiceServer interface {
	Draw(context.Context, *DrawRequest) (*DrawResponse, error)
	GetHistories(context.Context, *GetHistoriesRequest) (*GetHistoriesResponse, error)
	mustEmbedUnimplementedGachaServiceServer()
}

// UnimplementedGachaServiceServer must be embedded to have forward compatible implementations.
type UnimplementedGachaServiceServer struct {
}

func (UnimplementedGachaServiceServer) Draw(context.Context, *DrawRequest) (*DrawResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Draw not implemented")
}
func (UnimplementedGachaServiceServer) GetHistories(context.Context, *GetHistoriesRequest) (*GetHistoriesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetHistories not implemented")
}
func (UnimplementedGachaServiceServer) mustEmbedUnimplementedGachaServiceServer() {}

// UnsafeGachaServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GachaServiceServer will
// result in compilation errors.
type UnsafeGachaServiceServer interface {
	mustEmbedUnimplementedGachaServiceServer()
}

func RegisterGachaServiceServer(s grpc.ServiceRegistrar, srv GachaServiceServer) {
	s.RegisterService(&GachaService_ServiceDesc, srv)
}

func _GachaService_Draw_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DrawRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GachaServiceServer).Draw(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gacha.GachaService/Draw",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GachaServiceServer).Draw(ctx, req.(*DrawRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GachaService_GetHistories_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetHistoriesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GachaServiceServer).GetHistories(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gacha.GachaService/GetHistories",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GachaServiceServer).GetHistories(ctx, req.(*GetHistoriesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GachaService_ServiceDesc is the grpc.ServiceDesc for GachaService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GachaService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gacha.GachaService",
	HandlerType: (*GachaServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Draw",
			Handler:    _GachaService_Draw_Handler,
		},
		{
			MethodName: "GetHistories",
			Handler:    _GachaService_GetHistories_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/gacha.proto",
}
